# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject
    
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'SCLAlertView'

  target 'TestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
